### PR TITLE
Windows size is shrinking everytime App opens

### LINKED ISSUE #3129: [BUG] The height of Desktop Window shrinks unexpectedly
### Description
There is a weird bug that the Window size of Toggl desktop will become smaller after we resizing and relaunch.

See the GIF, the initial windows expands entire the GIF frame, but after re-launching, the windows is smaller.
 

### 💻 Environment
Platform: macOS
OS Version: macOS 10.14
Toggl Version: master at 38681c61b

### 🐞 Actual behavior
- Windows size is smaller after re-launching

### 💯 Expected behavior
- The windows size should be consistent before and after

### 🔨 Steps to reproduce
1. Open Toggl
2. Resize to any size
3. Quit
4. Open -> The size is lesser 💥

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
This PR will introduce the fix for this weird bug.

### 🕶️ Types of changes
 **Bug fix** (non-breaking change which fixes an issue)

### 🤯 List of changes
- [x] Set Window's properties of MainWindowController in initial phrase.

### 👫 Relationships
Close #3129 

### 🔎 Review hints
- Start the Toggl -> Check the initial size -> Stop -> Open again -> If the size is consistent -> 💯

### CODE REVIEW

File: src/ui/osx/TogglDesktop/MainWindowController.m [hunk 1]
```diff
@@ -80,11 +80,6 @@ - (void)windowDidLoad
 {
 	[super windowDidLoad];
 
-	// Clean window titlebar
-	self.window.titleVisibility = NSWindowTitleHidden;
-	self.window.titlebarAppearsTransparent = YES;
-	self.window.styleMask |= NSFullSizeContentViewWindowMask;
```
Comment (NghiaTranUIT) [inline src/ui/osx/TogglDesktop/MainWindowController.m]: The problem is here. As we set the `NSFullSizeContentViewWindowMask` for a main Window after initialization time (-windowDidLoad), so the content size will accidentally get smaller.

Thus, Override it in XIB is better way.

**Comment by IndrekV** [comment]
Well done! Very elegant solution!
