### PR TITLE
Fix/offline state

### LINKED ISSUE #2884: Improve offline capabilities of the apps
### 💻 Environment

Platform: All (library)

### 📒 Description
- Load more button keeps spinning (it should either not show the button offline or just hide it after the click)
- Entries do not get unsynced icons for some reason (fixed with f8a7644)
- We should validate data before sending so we can show proper error message without a network connection.
Example errors:
   - Too big duration. If the app is offline strange things starts to happen. The timer starts to count down. It happens even if you select a stopped entry and change duration to some big number (more than 999 hours that is allowed). it will start to count down.

    - Start/Stop time errors
`Stop time year must be between 2006 and 2030`

### PR DESCRIPTION
**Pull request by IndrekV**
### 📒 Description
App should work offline exactly the same as online. No functionality should be missing. This mostly goes to data validation and syncing errors.

### 🕶️ Types of changes

**Bug fix** (non-breaking change which fixes an issue)

### 🤯 List of changes
- Render entries list right away after sync fails. This means that you see unsynced icons right when the sync fails
- ... To be added

### 👫 Relationships

Closes #2884

### 🔎 Review hints

- Turn off internet connection
- Do a bunch of actions. (edit entries, start, stop, delete)
- See if unsynced icons are shown properly. Or if validation errors are displayed.
- If the internet is turned off the app should show unsynced icons for entries right after app start
- The app should not allow saving duration larger than 999 hrs. (3 596 400 seconds). It makes the duration 999hrs if the value is bigger.
- Error should be shown if the selected date is not between the year 2006 and 2030.
- Error should be shown if the description text is longer than 3000 characters.

### CODE REVIEW

File: src/formatter.cc [hunk 1]
```diff
@@ -370,9 +370,12 @@ int Formatter::ParseDurationString(const std::string value) {
 
     // 15
     if (input.find(".") == std::string::npos) {
-        int minutes = 0;
-        if (Poco::NumberParser::tryParse(input, minutes)) {
-            return seconds + (minutes * 60);
+        Poco::Int64 minutes = 0;
+        if (Poco::NumberParser::tryParse64(input, minutes)) {
+            if (minutes > kMaxDurationSeconds) {
+                return kMaxDurationSeconds;
```
Comment (NghiaTranUIT) [inline src/formatter.cc]: I'm suppose that If it's incorrect when we return `kMaxDurationSeconds` in `Formatter::ParseDurationString`.

Let take a following code as a typical example:

https://github.com/toggl/toggldesktop/blob/91d8d9fa02ea56ddb3fc42527a8584f2a31e808f/src/context.cc#L2790-L2793

Let imagine that in some scenario, the`Formatter::ParseDurationString` return `kMaxDurationSeconds`, but the 
```
return displayError(error(kOverMaxDurationError));
```
is never executed.

---------
I could be fixed by replacing with
```
if ((minutes * 60) > kMaxDurationSeconds) {
        return kMaxDurationSeconds + 1;
}
```

File: src/context.cc [hunk 2]
```diff
@@ -2941,6 +2952,11 @@ error Context::SetTimeEntryStart(
 
     Poco::LocalDateTime local(Poco::Timestamp::fromEpochTime(te->Start()));
 
+    // Validate time input
+    if (local.year() < kMinimumAllowedYear || local.year() > kMinimumAllowedYear) {
```
Comment (NghiaTranUIT) [inline src/context.cc]: This condition is wrong in my case when I try to edit the Start Time from `17:30` to `17:20`. Therefore, it presents invalid Year error.

Screen Shot 2019-04-02 at 10 47 49

## Attempt:

Screen Shot 2019-04-02 at 10 47 35

The `local.year()` return `106` (in console), but `local._year` is `2019`

Comment (NghiaTranUIT) [reply src/context.cc]: For some reason, the `local.year()` returns wrong value event the TimeEntry's StartDate is correct 💭

File: src/context.cc [hunk 3]
```diff
@@ -2890,6 +2896,11 @@ error Context::SetTimeEntryDate(
         Poco::LocalDateTime time_part(
             Poco::Timestamp::fromEpochTime(te->Start()));
 
+        // Validate date input
+        if (date_part.year() < kMinimumAllowedYear || date_part.year() > kMinimumAllowedYear) {
```
Comment (NghiaTranUIT) [inline src/context.cc]: Same with my previous comment, we should double check whether `date_part.year()` returns correct value or not 🤔

File: src/context.cc (hunk 2 above)
Comment (IndrekV) [reply src/context.cc]: local.year actually returns the correct value. I'm not sure why console show other number. The issue was that in second check there should be `kMaximumAllowedYear`.

File: src/formatter.cc (hunk 1 above)
Comment (IndrekV) [reply src/formatter.cc]: I think the `kMaxDurationSeconds + 1` is not needed we can just use
```
if (seconds >= kMaxDurationSeconds) { 
     return displayError(error(kOverMaxDurationError)); 
 }
```
In `context.cc` and it will work. Fixed with (43093445d8947dff89c22e8e44c41685894d1b91)

**Comment by IndrekV** [comment]
I've fixed all the reported issues. It's now ready for a second review.
