### PR TITLE
Show reminder notification using custom UI

### LINKED ISSUE #2133: Reminder not working
I have set the desktop app to remind me every 10 min if I am not tracking time from 9:00 to 18:00 Monday-Friday. I have not received any reminder. 

Windows 10.

### LINKED ISSUE #2287: Tray icon is not removed when app is closed
If app is closed the tray icon stays in the tray. It disapears only when hovered. This might be caused by force closing or non graceful app quit. It seems that the `shutdown` method in `MainWindow.xaml.cs`is not called on quit.

### LINKED ISSUE #2583: Reminders not popping up - Windows Desktop app
"The reminder feature doesn't seem to work. It is enabled but I am not getting reminders.

I have tried clearing the cache and re-installing. "

conversations/18611274344

### PR DESCRIPTION
**Pull request by skel35**
### 📒 Description
In order to more reliably show reminder notifications, we are switching to our custom notifications UI, same as Autotracker and Pomodoro notifications are using currently.
image

### 🕶️ Types of changes
**Breaking change** (fix or feature that would cause existing functionality to change)

### 🤯 List of changes
- [x] Refactor Autotracker and Pomodoro notifications to make them share UI code via `TogglNotification` custom control
- [x] Introduce `ReminderNotification` control inheriting from `TogglNotification`
- [x] Show `ReminderNotification` instead of balloon tip
- [x] Update `Hardcodet.NotifyIcon.Wpf` NuGet package version
- [x] Dispose and remove the tray icon in PrepareShutdown() method #2287

### 👫 Relationships
Reminder notifications not showing up issues:
Closes #2583
Closes #2133 

Tray icon bug:
Closes #2287

### 🔎 Review hints
- Autotracker and Pomodoro notifications are displayed in the same way as before
- Reminder notification is being displayed using a custom UI. Clicking on the notification shows the main window. Clicking the `Start` button starts time entry and moves focus to the description in the Edit view.
- Balloon tips or toasts are not displayed anymore.

### CODE REVIEW

File: src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TogglNotification.cs [hunk 1]
```diff
@@ -0,0 +1,38 @@
+﻿using System.Windows;
+using System.Windows.Controls;
+
+namespace TogglDesktop
+{
+    public class TogglNotification : Control
```
Comment (Abdulbaqi-Alshareef) [inline src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TogglNotification.cs]:
```suggestion
    public class TogglNotification : ContentControl 
```
I think its more convenient to derive from ContentControl instead of Control and then you don't need to implement Content  dependency property

Comment (skel35) [reply src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TogglNotification.cs]: Agree, thx 👍

**Comment by IndrekV** [comment]
@skel35 I had to manually go into the nuget manager and update `Hardcodet.NotifyIcon.Wpf` to version 1.0.8 is it possible to somehow force the build process to detect and update this.

The solution works as expected.

**Comment by skel35** [comment]
@IndrekV There was an incorrect version, I made a mistake when resolving the merge conflict.
Fixed it.

**Comment by IndrekV** [comment]
👍
