### PR TITLE
ScopedLock for RelatedData.TimeEntries

### LINKED ISSUE #2506: Frequent Hangs and Crashes
Hi, 
In addition to becoming unresponsive on network connetion loss, I just got this crash today

<details>
<summary> crash log </summary>

```
Process:               TogglDesktop [2358]
Path:                  /Applications/TogglDesktop.app/Contents/MacOS/TogglDesktop
Identifier:            com.toggl.toggldesktop.TogglDesktop
Version:               7.4.170 (7.4.170)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           TogglDesktop [2358]
User ID:               501

Date/Time:             2018-06-27 14:57:11.411 -0500
OS Version:            Mac OS X 10.13.5 (17F77)
Report Version:        12
Anonymous UUID:        108FF5ED-4DAE-6503-F05C-32CF8ACA1621


Time Awake Since Boot: 8600 seconds

System Integrity Protection: enabled

Crashed Thread:        1

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Performing @selector(discardIdleAndContinue:) from sender NSButton 0x60000015a360

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_platform.dylib      	0x00007fff51c87c04 _platform_memset$VARIANT$Haswell + 4
1   libc++.1.dylib                	0x00007fff4f90049c std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(unsigned long, char) + 160
2   libc++.1.dylib                	0x00007fff4f9003dd std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::resize(unsigned long, char) + 39
3   TogglDesktopLibrary.dylib     	0x000000010593673f std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 159
4   TogglDesktopLibrary.dylib     	0x00000001059c92f5 toggl::TimeEntry::Tags() const + 297
5   TogglDesktopLibrary.dylib     	0x000000010596f4b5 toggl::view::TimeEntry::Fill(toggl::TimeEntry*) + 893
6   TogglDesktopLibrary.dylib     	0x000000010598ed3b toggl::Context::updateUI(toggl::UIElements const&) + 4843
7   TogglDesktopLibrary.dylib     	0x00000001059917d8 toggl::Context::save(bool) + 656
8   TogglDesktopLibrary.dylib     	0x00000001059aa8f3 toggl::Context::Continue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 319
9   TogglDesktopLibrary.dylib     	0x00000001059af408 toggl::Context::DiscardTimeAndContinue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long) + 898
10  TogglDesktopLibrary.dylib     	0x0000000105a2a19e toggl_discard_time_and_continue + 66
11  com.toggl.toggldesktop.TogglDesktop	0x000000010582d6e1 -[IdleNotificationWindowController discardIdleAndContinue:] + 167
12  com.apple.AppKit              	0x00007fff27897a43 -[NSApplication(NSResponder) sendAction:to:from:] + 312
13  com.apple.AppKit              	0x00007fff2733d53f -[NSControl sendAction:to:] + 86
14  com.apple.AppKit              	0x00007fff2733d467 __26-[NSCell _sendActionFrom:]_block_invoke + 136
15  com.apple.AppKit              	0x00007fff2733d36d -[NSCell _sendActionFrom:] + 183
16  com.apple.AppKit              	0x00007fff2737e688 -[NSButtonCell _sendActionFrom:] + 97
17  com.apple.AppKit              	0x00007fff2733bbd6 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 2438
18  com.apple.AppKit              	0x00007fff2737e3cf -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 777
19  com.apple.AppKit              	0x00007fff2733a670 -[NSControl mouseDown:] + 965
20  com.apple.AppKit              	0x00007fff27a36d6d -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5891
21  com.apple.AppKit              	0x00007fff27a339c4 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2359
22  com.apple.AppKit              	0x00007fff27a32c70 -[NSWindow(NSEventRouting) sendEvent:] + 497
23  com.apple.AppKit              	0x00007fff27894236 -[NSApplication(NSEvent) sendEvent:] + 2462
24  com.apple.AppKit              	0x00007fff270f48b5 -[NSApplication run] + 812
25  com.apple.AppKit              	0x00007fff270c3a72 NSApplicationMain + 804
26  libdyld.dylib                 	0x00007fff51975015 start + 1

Thread 1 Crashed:
0   TogglDesktopLibrary.dylib     	0x000000010595252c toggl::RelatedData::timeEntryAutocompleteItems(std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*, std::__1::vector<toggl::view::Autocomplete, std::__1::allocator<toggl::view::Autocomplete> >*) const + 170
1   TogglDesktopLibrary.dylib     	0x0000000105953c2f toggl::RelatedData::TimeEntryAutocompleteItems(std::__1::vector<toggl::view::Autocomplete, std::__1::allocator<toggl::view::Autocomplete> >*) const + 41
2   TogglDesktopLibrary.dylib     	0x0000000105993a9e toggl::Context::onTimeEntryAutocompletes(Poco::Util::TimerTask&) + 52
3   libPocoUtil.50.dylib          	0x0000000105ee21e9 Poco::Util::TaskNotification::execute() + 57
4   libPocoUtil.50.dylib          	0x0000000105ee1d89 Poco::Util::Timer::run() + 57
5   libPocoFoundation.50.dylib    	0x000000010632deb7 Poco::ThreadImpl::runnableEntry(void*) + 103
6   libsystem_pthread.dylib       	0x00007fff51c8d661 _pthread_body + 340
7   libsystem_pthread.dylib       	0x00007fff51c8d50d _pthread_start + 377
8   libsystem_pthread.dylib       	0x00007fff51c8cbf9 thread_start + 13

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff51ac5d8a __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff51a40724 nanosleep + 199
2   libPocoFoundation.50.dylib    	0x000000010632e4ef Poco::ThreadImpl::sleepImpl(long) + 143
3   TogglDesktopLibrary.dylib     	0x0000000105989e48 toggl::Context::uiUpdaterActivity() + 82
4   TogglDesktopLibrary.dylib     	0x00000001059be473 Poco::Activity<toggl::Context>::run() + 35
5   libPocoFoundation.50.dylib    	0x000000010633013a Poco::PooledThread::run() + 106
6   libPocoFoundation.50.dylib    	0x000000010632deb7 Poco::ThreadImpl::runnableEntry(void*) + 103
7   libsystem_pthread.dylib       	0x00007fff51c8d661 _pthread_body + 340
8   libsystem_pthread.dylib       	0x00007fff51c8d50d _pthread_start + 377
9   libsystem_pthread.dylib       	0x00007fff51c8cbf9 thread_start + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff51ac5d8a __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff51a40724 nanosleep + 199
2   libPocoFoundation.50.dylib    	0x000000010632e4ef Poco::ThreadImpl::sleepImpl(long) + 143
3   TogglDesktopLibrary.dylib     	0x000000010598a08e toggl::Context::reminderActivity() + 32
4   TogglDesktopLibrary.dylib     	0x00000001059be473 Poco::Activity<toggl::Context>::run() + 35
5   libPocoFoundation.50.dylib    	0x000000010633013a Poco::PooledThread::run() + 106
6   libPocoFoundation.50.dylib    	0x000000010632deb7 Poco::ThreadImpl::runnableEntry(void*) + 103
7   libsystem_pthread.dylib       	0x00007fff51c8d661 _pthread_body + 340
8   libsystem_pthread.dylib       	0x00007fff51c8d50d _pthread_start + 377
9   libsystem_pthread.dylib       	0x00007fff51c8cbf9 thread_start + 13

Thread 4:
0   libsystem_platform.dylib      	0x00007fff51c838ed OSAtomicDequeue + 17
1   libsystem_malloc.dylib        	0x00007fff51b24b9f nano_malloc + 35
2   libsystem_malloc.dylib        	0x00007fff51b1e1bd malloc_zone_malloc + 103
3   libsystem_malloc.dylib        	0x00007fff51b1d4c7 malloc + 24
4   libcrypto.1.1.dylib           	0x00000001065c6ebd CRYPTO_zalloc + 61
5   libcrypto.1.1.dylib           	0x000000010650408a asn1_item_embed_new + 698
6   libcrypto.1.1.dylib           	0x000000010650115b asn1_item_embed_d2i + 731
7   libcrypto.1.1.dylib           	0x0000000106502715 asn1_template_noexp_d2i + 597
8   libcrypto.1.1.dylib           	0x0000000106501810 asn1_template_ex_d2i + 80
9   libcrypto.1.1.dylib           	0x0000000106500fa9 asn1_item_embed_d2i + 297
10  libcrypto.1.1.dylib           	0x0000000106500e1d ASN1_item_d2i + 61
11  libcrypto.1.1.dylib           	0x0000000106646662 X509V3_get_d2i + 338
12  libcrypto.1.1.dylib           	0x000000010664934e x509v3_cache_extensions + 910
13  libcrypto.1.1.dylib           	0x0000000106648f23 X509_check_purpose + 51
14  libcrypto.1.1.dylib           	0x000000010662fd40 verify_chain + 80
15  libcrypto.1.1.dylib           	0x000000010662fbe1 X509_verify_cert + 673
16  libssl.1.1.dylib              	0x0000000106760110 ssl_verify_cert_chain + 480
17  libssl.1.1.dylib              	0x0000000106775528 tls_process_server_certificate + 440
18  libssl.1.1.dylib              	0x0000000106772293 state_machine + 1523
19  libPocoNetSSL.50.dylib        	0x0000000105f9a968 Poco::Net::SecureSocketImpl::connectSSL(bool) + 328
20  libPocoNetSSL.50.dylib        	0x0000000105f9acbb Poco::Net::SecureSocketImpl::connect(Poco::Net::SocketAddress const&, Poco::Timespan const&, bool) + 203
21  libPocoNetSSL.50.dylib        	0x0000000105f9e0ac Poco::Net::SecureStreamSocketImpl::connect(Poco::Net::SocketAddress const&, Poco::Timespan const&) + 28
22  libPocoNet.50.dylib           	0x00000001061b4ae6 Poco::Net::HTTPSession::connect(Poco::Net::SocketAddress const&) + 22
23  libPocoNetSSL.50.dylib        	0x0000000105f941b8 Poco::Net::HTTPSClientSession::connect(Poco::Net::SocketAddress const&) + 216
24  libPocoNet.50.dylib           	0x000000010619ac70 Poco::Net::HTTPClientSession::reconnect() + 144
25  libPocoNet.50.dylib           	0x000000010619a382 Poco::Net::HTTPClientSession::sendRequest(Poco::Net::HTTPRequest&) + 210
26  TogglDesktopLibrary.dylib     	0x000000010593c487 toggl::HTTPSClient::makeHttpRequest(toggl::HTTPSRequest) + 4737
27  TogglDesktopLibrary.dylib     	0x000000010593ab3d toggl::HTTPSClient::request(toggl::HTTPSRequest) + 65
28  TogglDesktopLibrary.dylib     	0x0000000105939720 toggl::HTTPSClient::Get(toggl::HTTPSRequest) + 82
29  TogglDesktopLibrary.dylib     	0x00000001059c3bb6 toggl::GoogleAnalyticsEvent::runTask() + 268
30  libPocoFoundation.50.dylib    	0x0000000106326365 Poco::Task::run() + 85
31  libPocoFoundation.50.dylib    	0x000000010633013a Poco::PooledThread::run() + 106
32  libPocoFoundation.50.dylib    	0x000000010632deb7 Poco::ThreadImpl::runnableEntry(void*) + 103
33  libsystem_pthread.dylib       	0x00007fff51c8d661 _pthread_body + 340
34  libsystem_pthread.dylib       	0x00007fff51c8d50d _pthread_start + 377
35  libsystem_pthread.dylib       	0x00007fff51c8cbf9 thread_start + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff51abc20a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff51abb724 mach_msg + 60
2   com.apple.SkyLight            	0x00007fff4b868ced SLWindowListCopyWindowInfo + 174
3   TogglDesktopLibrary.dylib     	0x0000000105934d74 getFocusedWindowInfo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool*) + 118
4   TogglDesktopLibrary.dylib     	0x00000001059352e8 toggl::WindowChangeRecorder::inspectFocusedWindow() + 68
5   TogglDesktopLibrary.dylib     	0x00000001059361e1 toggl::WindowChangeRecorder::recordLoop() + 93
6   TogglDesktopLibrary.dylib     	0x00000001059bcdf5 Poco::Activity<toggl::WindowChangeRecorder>::run() + 35
7   libPocoFoundation.50.dylib    	0x000000010633013a Poco::PooledThread::run() + 106
8   libPocoFoundation.50.dylib    	0x000000010632deb7 Poco::ThreadImpl::runnableEntry(void*) + 103
9   libsystem_pthread.dylib       	0x00007fff51c8d661 _pthread_body + 340
10  libsystem_pthread.dylib       	0x00007fff51c8d50d _pthread_start + 377
11  libsystem_pthread.dylib       	0x00007fff51c8cbf9 thread_start + 13

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff51ac5d8a __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff51a40724 nanosleep + 199
2   libPocoFoundation.50.dylib    	0x000000010632e4ef Poco::ThreadImpl::sleepImpl(long) + 143
3   TogglDesktopLibrary.dylib     	0x000000010596cdb2 toggl::TimelineUploader::sleep() + 38
4   TogglDesktopLibrary.dylib     	0x000000010596ced6 toggl::TimelineUploader::upload_loop_activity() + 274
5   TogglDesktopLibrary.dylib     	0x00000001059bd0af Poco::Activity<toggl::TimelineUploader>::run() + 35
6   libPocoFoundation.50.dylib    	0x000000010633013a Poco::PooledThread::run() + 106
7   libPocoFoundation.50.dylib    	0x000000010632deb7 Poco::ThreadImpl::runnableEntry(void*) + 103
8   libsystem_pthread.dylib       	0x00007fff51c8d661 _pthread_body + 340
9   libsystem_pthread.dylib       	0x00007fff51c8d50d _pthread_start + 377
10  libsystem_pthread.dylib       	0x00007fff51c8cbf9 thread_start + 13

Thread 7:
0   libsystem_kernel.dylib        	0x00007fff51ac5cfa __select + 10
1   libPocoNet.50.dylib           	0x00000001061a2354 Poco::Net::SocketImpl::poll(Poco::Timespan const&, int) + 436
2   TogglDesktopLibrary.dylib     	0x00000001059cfabe toggl::WebSocketClient::poll() + 78
3   TogglDesktopLibrary.dylib     	0x00000001059d04c4 toggl::WebSocketClient::runActivity() + 270
4   TogglDesktopLibrary.dylib     	0x00000001059d0fe3 Poco::Activity<toggl::WebSocketClient>::run() + 35
5   libPocoFoundation.50.dylib    	0x000000010633013a Poco::PooledThread::run() + 106
6   libPocoFoundation.50.dylib    	0x000000010632deb7 Poco::ThreadImpl::runnableEntry(void*) + 103
7   libsystem_pthread.dylib       	0x00007fff51c8d661 _pthread_body + 340
8   libsystem_pthread.dylib       	0x00007fff51c8d50d _pthread_start + 377
9   libsystem_pthread.dylib       	0x00007fff51c8cbf9 thread_start + 13

Thread 8:
0   libsystem_kernel.dylib        	0x00007fff51ac5a1e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff51c8e589 _pthread_cond_wait + 732
2   libPocoFoundation.50.dylib    	0x00000001062c2e36 Poco::EventImpl::waitImpl() + 70
3   libPocoFoundation.50.dylib    	0x0000000106330195 Poco::PooledThread::run() + 197
4   libPocoFoundation.50.dylib    	0x000000010632deb7 Poco::ThreadImpl::runnableEntry(void*) + 103
5   libsystem_pthread.dylib       	0x00007fff51c8d661 _pthread_body + 340
6   libsystem_pthread.dylib       	0x00007fff51c8d50d _pthread_start + 377
7   libsystem_pthread.dylib       	0x00007fff51c8cbf9 thread_start + 13

Thread 9:
0   libsystem_kernel.dylib        	0x00007fff51ac5a1e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff51c8e589 _pthread_cond_wait + 732
2   libPocoFoundation.50.dylib    	0x00000001062c2e36 Poco::EventImpl::waitImpl() + 70
3   libPocoFoundation.50.dylib    	0x0000000106330195 Poco::PooledThread::run() + 197
4   libPocoFoundation.50.dylib    	0x000000010632deb7 Poco::ThreadImpl::runnableEntry(void*) + 103
5   libsystem_pthread.dylib       	0x00007fff51c8d661 _pthread_body + 340
6   libsystem_pthread.dylib       	0x00007fff51c8d50d _pthread_start + 377
7   libsystem_pthread.dylib       	0x00007fff51c8cbf9 thread_start + 13

Thread 10:: com.apple.NSEventThread
0   libsystem_platform.dylib      	0x00007fff51c87c69 _platform_bzero$VARIANT$Haswell + 41
1   com.apple.SkyLight            	0x00007fff4b8b7058 SLEventCreateFromDataAndSource + 57
2   com.apple.SkyLight            	0x00007fff4b7ad99b CGSDecodeEventRecord + 72
3   com.apple.SkyLight            	0x00007fff4b7acb57 CGSSnarfAndDispatchDatagrams + 1714
4   com.apple.SkyLight            	0x00007fff4b83e47d SLSGetNextEventRecordInternal + 81
5   com.apple.SkyLight            	0x00007fff4b8b6e74 SLEventCreateNextEvent + 44
6   com.apple.HIToolbox           	0x00007fff28e579cf PullEventsFromWindowServerOnConnection(unsigned int, unsigned char, __CFMachPortBoost*) + 45
7   com.apple.HIToolbox           	0x00007fff28e57970 MessageHandler(__CFMachPort*, void*, long, void*) + 51
8   com.apple.CoreFoundation      	0x00007fff29b70596 __CFMachPortPerform + 310
9   com.apple.CoreFoundation      	0x00007fff29b70449 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
10  com.apple.CoreFoundation      	0x00007fff29b70395 __CFRunLoopDoSource1 + 533
11  com.apple.CoreFoundation      	0x00007fff29b67f50 __CFRunLoopRun + 2848
12  com.apple.CoreFoundation      	0x00007fff29b671a3 CFRunLoopRunSpecific + 483
13  com.apple.AppKit              	0x00007fff2723cfc4 _NSEventThread + 184
14  libsystem_pthread.dylib       	0x00007fff51c8d661 _pthread_body + 340
15  libsystem_pthread.dylib       	0x00007fff51c8d50d _pthread_start + 377
16  libsystem_pthread.dylib       	0x00007fff51c8cbf9 thread_start + 13

Thread 11:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	0x00007fff51abc20a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff51abb724 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff29b687d5 __CFRunLoopServiceMachPort + 341
3   com.apple.CoreFoundation      	0x00007fff29b67b27 __CFRunLoopRun + 1783
4   com.apple.CoreFoundation      	0x00007fff29b671a3 CFRunLoopRunSpecific + 483
5   com.apple.CFNetwork           	0x00007fff28cade78 -[__CoreSchedulingSetRunnable runForever] + 722
6   com.apple.Foundation          	0x00007fff2bc721f8 __NSThread__start__ + 1197
7   libsystem_pthread.dylib       	0x00007fff51c8d661 _pthread_body + 340
8   libsystem_pthread.dylib       	0x00007fff51c8d50d _pthread_start + 377
9   libsystem_pthread.dylib       	0x00007fff51c8cbf9 thread_start + 13

Thread 12:
0   libsystem_kernel.dylib        	0x00007fff51ac6292 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff51c8d009 _pthread_wqthread + 1035
2   libsystem_pthread.dylib       	0x00007fff51c8cbe9 start_wqthread + 13

Thread 13:
0   libsystem_kernel.dylib        	0x00007fff51ac6292 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff51c8d009 _pthread_wqthread + 1035
2   libsystem_pthread.dylib       	0x00007fff51c8cbe9 start_wqthread + 13

Thread 14:
0   libsystem_kernel.dylib        	0x00007fff51ac6292 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff51c8d009 _pthread_wqthread + 1035
2   libsystem_pthread.dylib       	0x00007fff51c8cbe9 start_wqthread + 13

Thread 15:
0   libsystem_kernel.dylib        	0x00007fff51ac6292 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff51c8d009 _pthread_wqthread + 1035
2   libsystem_pthread.dylib       	0x00007fff51c8cbe9 start_wqthread + 13

Thread 1 crashed with X86 Thread State (64-bit):
  rax: 0x0000604000232f20  rbx: 0x00007fd9a153baa0  rcx: 0x0000000000cad265  rdx: 0x0000000000cad264
  rdi: 0x00097fd9a16d9240  rsi: 0x0000000000000008  rbp: 0x0000700003b22dd0  rsp: 0x0000700003b22a90
   r8: 0x0000000000000020   r9: 0x00007fd9a202ae08  r10: 0x0000000000000001  r11: 0xffffffffffbdd1c0
  r12: 0x0000700003b22bc0  r13: 0x00007fd9a1539658  r14: 0x00007fd9a1511c80  r15: 0x0000000105add050
  rip: 0x000000010595252c  rfl: 0x0000000000000287  cr2: 0x0000000118e042a5
  
Logical CPU:     0
Error Code:      0x020000b8
Trap Number:     133


Binary Images:
       0x1057ec000 -        0x105873fff +com.toggl.toggldesktop.TogglDesktop (7.4.170 - 7.4.170) <45978C3A-3D47-3C37-919C-692533136679> /Applications/TogglDesktop.app/Contents/MacOS/TogglDesktop
       0x10592f000 -        0x105ad9fff +TogglDesktopLibrary.dylib (0) <02D69BD4-3D2E-3001-81B9-23CF42A2064E> /Applications/TogglDesktop.app/Contents/Frameworks/TogglDesktopLibrary.dylib
       0x105b98000 -        0x105bc4fff +coop.plausible.CrashReporter (1.0) <288B1309-4488-3E28-8E7D-95490264514B> /Applications/TogglDesktop.app/Contents/Frameworks/CrashReporter.framework/Versions/A/CrashReporter
       0x105c07000 -        0x105c0dff7 +com.wannabegeek.TFDatePicker (1.0 - 1) <48EE631C-A6BB-3C93-BC35-368019A0D1BF> /Applications/TogglDesktop.app/Contents/Frameworks/TFDatePicker.framework/Versions/A/TFDatePicker
       0x105c1f000 -        0x105c4eff7 +org.andymatuschak.Sparkle (1.8.0 git - a0716aa) <7CD76F91-77EB-3240-9F18-AFB8942D7A18> /Applications/TogglDesktop.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x105c89000 -        0x105dd9ffb +libPocoData.50.dylib (0) <BF4705A3-0BDA-33F6-B12D-E24A66CF8811> /Applications/TogglDesktop.app/Contents/Frameworks/libPocoData.50.dylib
       0x105ec4000 -        0x105efcff7 +libPocoUtil.50.dylib (0) <045B9C2D-EE24-3E86-A969-BFEAB7852467> /Applications/TogglDesktop.app/Contents/Frameworks/libPocoUtil.50.dylib
       0x105f3b000 -        0x105f65ff7 +libPocoJSON.50.dylib (0) <F151E121-B644-3823-B9F7-A75A29BD20F9> /Applications/TogglDesktop.app/Contents/Frameworks/libPocoJSON.50.dylib
       0x105f8e000 -        0x105fafff3 +libPocoNetSSL.50.dylib (0) <26DA4804-85B3-3EE8-8905-9BDD4899B547> /Applications/TogglDesktop.app/Contents/Frameworks/libPocoNetSSL.50.dylib
       0x105fdb000 -        0x106034ff7 +libPocoXML.50.dylib (0) <C52A2697-B005-3B88-9D75-9AE710BB248A> /Applications/TogglDesktop.app/Contents/Frameworks/libPocoXML.50.dylib
       0x10607d000 -        0x106121ff7 +libPocoDataSQLite.50.dylib (0) <06615B97-95D5-3A1E-8B42-CE683E1FAA30> /Applications/TogglDesktop.app/Contents/Frameworks/libPocoDataSQLite.50.dylib
       0x106178000 -        0x106212ff7 +libPocoNet.50.dylib (0) <F5672A85-FA4C-318F-A9DB-D6CAEFE25140> /Applications/TogglDesktop.app/Contents/Frameworks/libPocoNet.50.dylib
       0x1062a3000 -        0x1063d0ff7 +libPocoFoundation.50.dylib (0) <E573256F-DD46-348E-9D98-C2CFF801611F> /Applications/TogglDesktop.app/Contents/Frameworks/libPocoFoundation.50.dylib
       0x106493000 -        0x1064b3fff +libPocoCrypto.50.dylib (0) <CF355D7A-835C-37A5-AA93-090616761AD9> /Applications/TogglDesktop.app/Contents/Frameworks/libPocoCrypto.50.dylib
       0x1064db000 -        0x1066c05df +libcrypto.1.1.dylib (0) <BA9BA119-9831-357E-94D4-6C5A1AB45C7F> /Applications/TogglDesktop.app/Contents/Frameworks/libcrypto.1.1.dylib
       0x10674f000 -        0x10679fff7 +libssl.1.1.dylib (0) <46DE760C-98CE-3103-8F42-F64B3FC28DB9> /Applications/TogglDesktop.app/Contents/Frameworks/libssl.1.1.dylib
       0x109000000 -        0x10904a9df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld
    0x7fff22097000 -     0x7fff223e5fff  com.apple.RawCamera.bundle (8.04.0 - 1017.3.7) <15D4D6E1-3F7B-3AFE-ADD8-EEBE2E461A94> /System/Library/CoreServices/RawCamera.bundle/Contents/MacOS/RawCamera
    0x7fff239f4000 -     0x7fff23a79ff7  com.apple.driver.AppleIntelHD5000GraphicsMTLDriver (10.34.27 - 10.3.4) <39803D49-8A24-3923-9B97-2EEC492D07A8> /System/Library/Extensions/AppleIntelHD5000GraphicsMTLDriver.bundle/Contents/MacOS/AppleIntelHD5000GraphicsMTLDriver
    0x7fff25cb9000 -     0x7fff25e99ff3  com.apple.avfoundation (2.0 - 1536.25) <CD6C9798-DC03-3CAB-873B-1710D1EEF743> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff25e9a000 -     0x7fff25f53fff  com.apple.audio.AVFAudio (1.0 - ???) <ECE63BA3-4344-3522-904B-71F89677AC7D> /System/Library/Frameworks/AVFoundation.framework/Versions/A/Frameworks/AVFAudio.framework/Versions/A/AVFAudio
    0x7fff26059000 -     0x7fff26059fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <8632A9C5-19EA-3FD7-A44D-80765CC9C540> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff2605a000 -     0x7fff26070fef  libCGInterfaces.dylib (417.2) <2E67702C-75F6-308A-A023-F28120BEE667> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
    0x7fff26071000 -     0x7fff2656ffc3  com.apple.vImage (8.1 - ???) <A243A7EF-0C8E-3A9A-AA38-44AFD7507F00> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
    0x7fff26570000 -     0x7fff266cafe3  libBLAS.dylib (1211.50.2) <62C659EB-3E32-3B5F-83BF-79F5DF30D5CE> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    0x7fff266cb000 -     0x7fff266f9fef  libBNNS.dylib (38.1) <7BAEFDCA-3227-3E07-80D8-59B6370B89C6> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
    0x7fff266fa000 -     0x7fff26ab9ff7  libLAPACK.dylib (1211.50.2) <40ADBA5F-8B2D-30AC-A7AD-7B17C37EE52D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    0x7fff26aba000 -     0x7fff26acfff7  libLinearAlgebra.dylib (1211.50.2) <E8E0B7FD-A0B7-31E5-AF01-81781F71EBBE> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
    0x7fff26ad0000 -     0x7fff26ad5ff3  libQuadrature.dylib (3) <3D6BF66A-55B2-3692-BAC7-DEB0C676ED29> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
    0x7fff26ad6000 -     0x7fff26b56fff  libSparse.dylib (79.50.2) <0DC25CDD-F8C1-3D6E-B472-8B060708424F> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparse.dylib
    0x7fff26b57000 -     0x7fff26b6afff  libSparseBLAS.dylib (1211.50.2) <722573CC-31CC-34B2-9032-E4F652A9CCFE> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
    0x7fff26b6b000 -     0x7fff26d18fc3  libvDSP.dylib (622.50.5) <40690941-CF89-3F90-A0AC-A4D200744A5D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
    0x7fff26d19000 -     0x7fff26dcafff  libvMisc.dylib (622.50.5) <BA2532DF-2D68-3DD0-9B59-D434BF702AA4> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
    0x7fff26dcb000 -     0x7fff26dcbfff  com.apple.Accelerate.vecLib (3.11 - vecLib 3.11) <54FF3B43-E66C-3F36-B34B-A2B3B0A36502> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    0x7fff270be000 -     0x7fff27f1cfff  com.apple.AppKit (6.9 - 1561.40.112) <2D9940B9-9C9B-3FF1-8E9F-26CD7E7E3B5A> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff27f6e000 -     0x7fff27f6efff  com.apple.ApplicationServices (48 - 50) <7BD49390-6D89-3429-80CD-6C70334F9B49> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff27f6f000 -     0x7fff27fd5fff  com.apple.ApplicationServices.ATS (377 - 445.4) <85E779EE-0219-3181-B4C4-201E4CC82AB5> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
    0x7fff2806e000 -     0x7fff28190fff  libFontParser.dylib (222.1.6) <6CEBACDD-B848-302E-B4B2-630CB16E663E> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib
    0x7fff28191000 -     0x7fff281dbff7  libFontRegistry.dylib (221.3) <C84F7112-4764-3F4B-9FBA-4A022CF6346B> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
    0x7fff28280000 -     0x7fff282b3ff7  libTrueTypeScaler.dylib (222.1.6) <9147F859-8BD9-31D9-AB54-8E9549B92AE9> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libTrueTypeScaler.dylib
    0x7fff2831d000 -     0x7fff28321ff3  com.apple.ColorSyncLegacy (4.13.0 - 1) <A5FB2694-1559-34A8-A3D3-2029F68A63CA> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/A/ColorSyncLegacy
    0x7fff283c1000 -     0x7fff28413ffb  com.apple.HIServices (1.22 - 624.1) <66FD9ED2-9630-313C-86AE-4C2FBCB3F351> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
    0x7fff28414000 -     0x7fff28422fff  com.apple.LangAnalysis (1.7.0 - 1.7.0) <B65FF7E6-E9B5-34D8-8CA7-63D415A8A9A6> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
    0x7fff28423000 -     0x7fff2846ffff  com.apple.print.framework.PrintCore (13.4 - 503.2) <B90C67C1-0292-3CEC-885D-F1882CD104BE> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
    0x7fff28470000 -     0x7fff284aafff  com.apple.QD (3.12 - 404.2) <38B20AFF-9D54-3B52-A6DC-C0D71380AA5F> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
    0x7fff284ab000 -     0x7fff284b7fff  com.apple.speech.synthesis.framework (7.5.1 - 7.5.1) <84ADDF38-36F1-3D3B-B28D-8865FA10FCD7> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
    0x7fff284b8000 -     0x7fff28745ff7  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <4545D879-3520-36D1-A83D-F3993CC2FA6B> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff28747000 -     0x7fff28747fff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <2EC5D9A6-EB65-32D8-9740-91D293626705> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff28a6a000 -     0x7fff28e04ff7  com.apple.CFNetwork (901.1 - 901.1) <5181E03E-F354-35D6-949B-79433346510B> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff28e19000 -     0x7fff28e19fff  com.apple.Carbon (158 - 158) <F8B370D9-2103-3276-821D-ACC756167F86> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff28e1a000 -     0x7fff28e1dffb  com.apple.CommonPanels (1.2.6 - 98) <2391761C-5CAA-3F68-86B7-50B37927B104> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
    0x7fff28e1e000 -     0x7fff29123fff  com.apple.HIToolbox (2.1.1 - 911.10) <EFE04E77-F288-3EC9-B7B4-C4C7C29D55EE> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7fff29124000 -     0x7fff29127ffb  com.apple.help (1.3.8 - 66) <DEBADFA8-C189-3195-B0D6-A1F2DE95882A> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
    0x7fff29128000 -     0x7fff2912dfff  com.apple.ImageCapture (9.0 - 9.0) <23B4916F-3B43-3DFF-B956-FC390EECA284> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
    0x7fff2912e000 -     0x7fff291c3ffb  com.apple.ink.framework (10.9 - 221) <5206C8B0-22DA-36C9-998E-846EDB626D5B> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
    0x7fff291c4000 -     0x7fff291deff7  com.apple.openscripting (1.7 - 174) <1B2A1F9E-5534-3D61-83CA-9199B39E8708> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
    0x7fff291ff000 -     0x7fff29200fff  com.apple.print.framework.Print (12 - 267) <3682ABFB-2561-3419-847D-02C247F4800D> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
    0x7fff29201000 -     0x7fff29203ff7  com.apple.securityhi (9.0 - 55006) <C1406B8D-7D05-3959-808F-9C82189CF57F> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
    0x7fff29204000 -     0x7fff2920afff  com.apple.speech.recognition.framework (6.0.3 - 6.0.3) <2ED8643D-B0C3-3F17-82A2-BBF13E6CBABC> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
    0x7fff2932b000 -     0x7fff2932bfff  com.apple.Cocoa (6.11 - 22) <4CF8E31C-B5C7-367B-B73D-1A8AC8E41B7F> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff29339000 -     0x7fff293f2fff  com.apple.ColorSync (4.13.0 - 3325) <D283C285-447D-3258-A7E4-59532123B8FF> /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync
    0x7fff2957f000 -     0x7fff29612ff7  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <222E098D-96E5-3669-B077-3C019111849A> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff29679000 -     0x7fff296a2ffb  com.apple.CoreBluetooth (1.0 - 1) <E1335074-9D07-370E-8440-61C4874BAC56> /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
    0x7fff296a3000 -     0x7fff299f9fef  com.apple.CoreData (120 - 851) <A2B59780-FB16-36A3-8EE0-E0EF072454E0> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fff299fa000 -     0x7fff29ae1fff  com.apple.CoreDisplay (1.0 - 97.21) <88E1D7C8-90F4-3F2C-A92B-5AB30B0468C8> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
    0x7fff29ae2000 -     0x7fff29f83fef  com.apple.CoreFoundation (6.9 - 1452.23) <945E5C0A-86C5-336E-A64F-5BF06E78985A> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff29f85000 -     0x7fff2a595fef  com.apple.CoreGraphics (2.0 - 1161.21) <27409F13-49A9-3C56-A9C6-D526C8FEEAD8> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff2a597000 -     0x7fff2a886fff  com.apple.CoreImage (13.0.0 - 579.5) <2B007515-7D90-3D64-8B5D-3B45DF648BFF> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fff2ab15000 -     0x7fff2ac0bffb  com.apple.CoreMedia (1.0 - 2276.50) <532FC472-3D02-39B5-8F48-5F14A35E5695> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff2ac0c000 -     0x7fff2ac5afff  com.apple.CoreMediaIO (812.0 - 4994) <57006022-B279-3DAD-8E7C-573D215746D2> /System/Library/Frameworks/CoreMediaIO.framework/Versions/A/CoreMediaIO
    0x7fff2ac5b000 -     0x7fff2ac5bfff  com.apple.CoreServices (822.33 - 822.33) <1AC8CE39-003D-3901-909F-2DE6838AF097> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff2ac5c000 -     0x7fff2acd0ffb  com.apple.AE (735.1 - 735.1) <08EBA184-20F7-3725-AEA6-C314448161C6> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fff2acd1000 -     0x7fff2afa8fff  com.apple.CoreServices.CarbonCore (1178.4 - 1178.4) <0D5E19BF-18CB-3FA4-8A5F-F6C787C5EE08> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff2afa9000 -     0x7fff2afddfff  com.apple.DictionaryServices (1.2 - 284.2) <6505B075-41C3-3C62-A4C3-85CE3F6825CD> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fff2afde000 -     0x7fff2afe6ffb  com.apple.CoreServices.FSEvents (1239.50.1 - 1239.50.1) <3637CEC7-DF0E-320E-9634-44A442925C65> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
    0x7fff2afe7000 -     0x7fff2b1a4fff  com.apple.LaunchServices (822.32 - 822.32) <2C93AAC9-6B22-3436-AC33-1BD414DCD66A> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fff2b1a5000 -     0x7fff2b255ff7  com.apple.Metadata (10.7.0 - 1191.4.13) <B5C22E70-C265-3C9F-865F-B138994A418D> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fff2b256000 -     0x7fff2b2b6fff  com.apple.CoreServices.OSServices (822.33 - 822.33) <856D17AF-2697-3838-980B-6B3AAFEE4BF9> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fff2b2b7000 -     0x7fff2b325fff  com.apple.SearchKit (1.4.0 - 1.4.0) <3662545A-B1CF-3079-BDCD-C83855CEFEEE> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fff2b326000 -     0x7fff2b34affb  com.apple.coreservices.SharedFileList (71.21 - 71.21) <1B5228EF-D869-3A50-A373-7F4B0289FADD> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
    0x7fff2b5eb000 -     0x7fff2b73bfff  com.apple.CoreText (352.0 - 578.18) <B8454115-2A4B-3585-A7A1-B47A638F2EEB> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff2b73c000 -     0x7fff2b776fff  com.apple.CoreVideo (1.8 - 0.0) <86CCC036-51BB-3DD1-9601-D93798BCCD0F> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff2b777000 -     0x7fff2b802ff3  com.apple.framework.CoreWLAN (13.0 - 1350.1) <E862CC02-69D2-3503-887B-B6E8223081E7> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff2ba7d000 -     0x7fff2ba82fff  com.apple.DiskArbitration (2.7 - 2.7) <B059E12C-94EA-3A39-A03F-8AAB5F4EE1F2> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff2bc1c000 -     0x7fff2bc1eff3  com.apple.ExceptionHandling (1.5 - 12) <66F613CE-62BE-31C0-9F52-DCC2DAB762CA> /System/Library/Frameworks/ExceptionHandling.framework/Versions/A/ExceptionHandling
    0x7fff2bc43000 -     0x7fff2c009fff  com.apple.Foundation (6.9 - 1452.23) <E64540AD-1755-3C16-8537-552A00E92541> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff2c079000 -     0x7fff2c0a9fff  com.apple.GSS (4.0 - 2.0) <41087278-74AE-3FA5-8C0E-9C78EB696299> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
    0x7fff2c1bb000 -     0x7fff2c2bfffb  com.apple.Bluetooth (6.0.6 - 6.0.6f2) <6EFCF45B-E80B-3D6C-8729-0C5F9E19DB85> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fff2c31f000 -     0x7fff2c3baff7  com.apple.framework.IOKit (2.0.2 - 1445.60.1) <7C16F358-1F63-349F-AD58-F7B287C7B7B7> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff2c3bc000 -     0x7fff2c3c3ffb  com.apple.IOSurface (211.12 - 211.12) <392CA7DE-B365-364E-AF4A-33EC2CC48E6F> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff2c3c4000 -     0x7fff2c419ff3  com.apple.ImageCaptureCore (7.0 - 7.0) <0DAB3D7E-8C3F-35DE-96DF-C370AD35EB65> /System/Library/Frameworks/ImageCaptureCore.framework/Versions/A/ImageCaptureCore
    0x7fff2c41a000 -     0x7fff2c594ff7  com.apple.ImageIO.framework (3.3.0 - 1739.3) <7C579D3F-AE0B-31C9-8F80-67F2290B8DE0> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff2c595000 -     0x7fff2c599ffb  libGIF.dylib (1739.3) <7AA44C9D-48E8-3090-B044-61FE6F0AEF38> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
    0x7fff2c59a000 -     0x7fff2c681fef  libJP2.dylib (1739.3) <AEBF7260-0C10-30C0-8F0F-8B347DEE78B3> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
    0x7fff2c682000 -     0x7fff2c6a5ff7  libJPEG.dylib (1739.3) <D8C966AD-A00C-3E8B-A7ED-D7CC7ECB3224> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
    0x7fff2c981000 -     0x7fff2c9a7feb  libPng.dylib (1739.3) <1737F680-99D1-3F03-BFA5-5CDA30EB880A> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
    0x7fff2c9a8000 -     0x7fff2c9aaffb  libRadiance.dylib (1739.3) <21746434-FCC7-36DE-9331-11277DF66AA8> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
    0x7fff2c9ab000 -     0x7fff2c9f9fef  libTIFF.dylib (1739.3) <C4CB5C1D-20F2-3BD4-B0E6-629FDB3EF8E8> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
    0x7fff2cbb5000 -     0x7fff2d89bfff  com.apple.JavaScriptCore (13605 - 13605.2.8) <B1955CFF-9343-301B-A297-AC58F3CE47E2> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff2d8b3000 -     0x7fff2d8ccff7  com.apple.Kerberos (3.0 - 1) <F86DCCDF-93C1-38B3-82C2-477C12E8EE6D> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
    0x7fff2db8b000 -     0x7fff2db92fff  com.apple.MediaAccessibility (1.0 - 114) <9F72AACD-BAEB-3646-BD0F-12C47591C20D> /System/Library/Frameworks/MediaAccessibility.framework/Versions/A/MediaAccessibility
    0x7fff2dc42000 -     0x7fff2e2abfff  com.apple.MediaToolbox (1.0 - 2276.50) <805401B7-E013-32DB-AA73-E835328FA601> /System/Library/Frameworks/MediaToolbox.framework/Versions/A/MediaToolbox
    0x7fff2e2ad000 -     0x7fff2e32eff7  com.apple.Metal (125.25 - 125.25) <E804AB5C-43A9-3216-9930-652595E0BFE5> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff2e34b000 -     0x7fff2e366fff  com.apple.MetalPerformanceShaders.MPSCore (1.0 - 1) <0B4455FE-5C97-345C-B416-325EC6D88A2A> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSCore.framework/Versions/A/MPSCore
    0x7fff2e367000 -     0x7fff2e3d6fef  com.apple.MetalPerformanceShaders.MPSImage (1.0 - 1) <87F14199-C445-34C2-90F8-57C29212483E> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSImage.framework/Versions/A/MPSImage
    0x7fff2e3d7000 -     0x7fff2e3fbfff  com.apple.MetalPerformanceShaders.MPSMatrix (1.0 - 1) <BD50FD9C-CE92-34AF-8663-968BF89202A0> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSMatrix.framework/Versions/A/MPSMatrix
    0x7fff2e3fc000 -     0x7fff2e4e3ff7  com.apple.MetalPerformanceShaders.MPSNeuralNetwork (1.0 - 1) <FBDDCAE6-EC6E-361F-B924-B3EBDEAC2D2F> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork
    0x7fff2e4e4000 -     0x7fff2e4e4ff7  com.apple.MetalPerformanceShaders.MetalPerformanceShaders (1.0 - 1) <20ECB52B-B5C2-39EA-88E3-DFEC0C3CC9FF> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
    0x7fff2f4e3000 -     0x7fff2f4efffb  com.apple.NetFS (6.0 - 4.0) <471DD96F-FA2E-3FE9-9746-2519A6780D1A> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
    0x7fff322e1000 -     0x7fff3232ffff  com.apple.opencl (2.8.15 - 2.8.15) <23D7B57E-F538-3B2F-ABE0-91A2AC7C3FE6> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
    0x7fff32330000 -     0x7fff3234cffb  com.apple.CFOpenDirectory (10.13 - 207.50.1) <3A8DECB8-52E6-3426-997B-1EF60DF47B28> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fff3234d000 -     0x7fff32358fff  com.apple.OpenDirectory (10.13 - 207.50.1) <13668964-818C-347A-9EBA-7C86CBFB33EA> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
    0x7fff334d7000 -     0x7fff334d9fff  libCVMSPluginSupport.dylib (16.5.10) <BF5D065A-A38B-3446-9418-799F598072EF> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
    0x7fff334da000 -     0x7fff334dfffb  libCoreFSCache.dylib (162.6.1) <879B2738-2E8A-3596-AFF8-9C3FB1B6828B> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
    0x7fff334e0000 -     0x7fff334e4fff  libCoreVMClient.dylib (162.6.1) <64ED0A84-225F-39BC-BE0D-C896ACF5B50A> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
    0x7fff334e5000 -     0x7fff334eeff7  libGFXShared.dylib (16.5.10) <6024B1FE-ACD7-3314-B390-85972CB9B778> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
    0x7fff334ef000 -     0x7fff334fafff  libGL.dylib (16.5.10) <AB8B6C73-8496-3784-83F6-27737ED03B09> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
    0x7fff334fb000 -     0x7fff33536fe7  libGLImage.dylib (16.5.10) <5B41D074-3132-3587-91B6-E441BA8C9F13> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
    0x7fff336a4000 -     0x7fff336e2ffb  libGLU.dylib (16.5.10) <F6844912-1B86-34DF-9FB5-A428CC7B5B18> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
    0x7fff3405a000 -     0x7fff34069fff  com.apple.opengl (16.5.10 - 16.5.10) <D51C7DE3-ABE0-3CED-BB9C-7D71C3205FB6> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff343e3000 -     0x7fff3452fff7  com.apple.QTKit (7.7.3 - 3014.8) <FEDEF531-50A3-32AB-A546-E6BA994C58E1> /System/Library/Frameworks/QTKit.framework/Versions/A/QTKit
    0x7fff34530000 -     0x7fff34795ff7  com.apple.imageKit (3.0 - 1043) <269244BB-A86E-3248-91D3-7B412D1899C6> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit
    0x7fff34796000 -     0x7fff34885ffb  com.apple.PDFKit (1.0 - 677.67) <6BD11C23-1AEA-3078-8D0C-A7152BCF9031> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/PDFKit.framework/Versions/A/PDFKit
    0x7fff34886000 -     0x7fff34d98ff7  com.apple.QuartzComposer (5.1 - 364) <1369D6DA-8842-3878-B546-1D09828331F5> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
    0x7fff34d99000 -     0x7fff34dbcfff  com.apple.quartzfilters (1.10.0 - 1.10.0) <C95CB89D-148D-341B-BC50-82D8C32BF767> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzFilters.framework/Versions/A/QuartzFilters
    0x7fff34dbd000 -     0x7fff34eb6ff7  com.apple.QuickLookUIFramework (5.0 - 743.13) <09B296B3-4242-3224-9F44-5DFB4AB894CC> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuickLookUI.framework/Versions/A/QuickLookUI
    0x7fff34eb7000 -     0x7fff34eb7fff  com.apple.quartzframework (1.5 - 21) <DCEB0FCC-2C32-3D02-8752-7B6FA009AB85> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff34eb8000 -     0x7fff35104ff7  com.apple.QuartzCore (1.11 - 584.52.1) <1E11741B-1AEF-34EC-944B-845DD62718F4> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff35105000 -     0x7fff3515cff7  com.apple.QuickLookFramework (5.0 - 743.13) <8254FFF2-EE0D-323D-A6F3-BEB59615EE47> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff35321000 -     0x7fff35338ff7  com.apple.SafariServices.framework (13605 - 13605.2.8) <AD7B1A9A-E162-3431-83FD-B961973E10C7> /System/Library/Frameworks/SafariServices.framework/Versions/A/SafariServices
    0x7fff35938000 -     0x7fff35c61fff  com.apple.security (7.0 - 58286.60.28) <12632D59-7FC2-3C37-AEAE-E9EB2A4253C3> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff35c62000 -     0x7fff35ceeff7  com.apple.securityfoundation (6.0 - 55185.50.5) <0AF578A7-F076-3CC5-A5B7-FCA065D8CB74> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
    0x7fff35d20000 -     0x7fff35d24ffb  com.apple.xpc.ServiceManagement (1.0 - 1) <2DE3DCFE-B463-35B4-8823-D8B6D799B654> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff360c9000 -     0x7fff36139ff3  com.apple.SystemConfiguration (1.17 - 1.17) <8532B8E9-7E30-35A3-BC4A-DDE8E0614FDA> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff362ee000 -     0x7fff36669fff  com.apple.VideoToolbox (1.0 - 2276.50) <882F0FAF-30C6-3052-BB93-F1875F41E419> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff36911000 -     0x7fff36e70feb  libwebrtc.dylib (7605.2.8) <41D91BDA-0289-31BC-9557-4B094A2CBDD3> /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libwebrtc.dylib
    0x7fff36e71000 -     0x7fff38543fff  com.apple.WebCore (13605 - 13605.2.8) <CCD710E1-80AD-3E82-BF78-F142EBB9895C> /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/WebCore
    0x7fff38544000 -     0x7fff3872bff3  com.apple.WebKitLegacy (13605 - 13605.2.8) <924E583D-87A0-3A8B-A151-91CEDF7EDE4A> /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebKitLegacy.framework/Versions/A/WebKitLegacy
    0x7fff3872c000 -     0x7fff38bc4ff3  com.apple.WebKit (13605 - 13605.2.8) <A54CA8D2-1B53-3957-A6B8-1329332B7001> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff39034000 -     0x7fff390c7fef  com.apple.APFS (1.0 - 1) <1C3D9229-E64A-3D11-ACDE-76E8171F7B7C> /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS
    0x7fff39ced000 -     0x7fff39d15fff  com.apple.framework.Apple80211 (13.0 - 1361.7) <16627876-8CF5-3502-A1D6-35FCBDD5E79A> /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Apple80211
    0x7fff39d17000 -     0x7fff39d26fef  com.apple.AppleFSCompression (96.60.1 - 1.0) <A7C875C4-F5EE-3272-AFB6-57C9FD5352B3> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
    0x7fff39e68000 -     0x7fff39eb0ff3  com.apple.AppleJPEG (1.0 - 1) <8DD410CB-76A1-3F22-9A9F-0491FA0CEB4A> /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
    0x7fff39eeb000 -     0x7fff39f13fff  com.apple.applesauce (1.0 - ???) <CCA8B094-1BCE-3AE3-A0A7-D544C818DE36> /System/Library/PrivateFrameworks/AppleSauce.framework/Versions/A/AppleSauce
    0x7fff39fdc000 -     0x7fff39fdfff3  com.apple.AppleSystemInfo (3.1.5 - 3.1.5) <0E33401D-7B9C-378A-8EE8-0E3D40B63C8D> /System/Library/PrivateFrameworks/AppleSystemInfo.framework/Versions/A/AppleSystemInfo
    0x7fff39fe0000 -     0x7fff3a030ff7  com.apple.AppleVAFramework (5.0.41 - 5.0.41) <8169ABC4-56F0-301E-B913-A762F7E40DBF> /System/Library/PrivateFrameworks/AppleVA.framework/Versions/A/AppleVA
    0x7fff3a735000 -     0x7fff3a73cff7  com.apple.coreservices.BackgroundTaskManagement (1.0 - 57.1) <51A41CA3-DB1D-3380-993E-99C54AEE518E> /System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Versions/A/BackgroundTaskManagement
    0x7fff3a73d000 -     0x7fff3a7c4ff7  com.apple.backup.framework (1.9.5 - 1.9.5) <8BCFB4DB-BAF0-328B-A019-FE13837AD154> /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup
    0x7fff3a7cd000 -     0x7fff3a7d3ff3  com.apple.BezelServicesFW (305 - 305) <FEED193D-3363-3C8A-9815-4A6128E640E3> /System/Library/PrivateFrameworks/BezelServices.framework/Versions/A/BezelServices
    0x7fff3b5a2000 -     0x7fff3b5f1ff3  com.apple.ChunkingLibrary (189 - 189) <C021A0EB-82E7-3A1E-A772-96B0E7E038D9> /System/Library/PrivateFrameworks/ChunkingLibrary.framework/Versions/A/ChunkingLibrary
    0x7fff3b5f8000 -     0x7fff3b689ff7  com.apple.CloudDocs (1.0 - 575.14) <7B39EEBE-88FA-39B9-BB89-F2AE6DF9FB50> /System/Library/PrivateFrameworks/CloudDocs.framework/Versions/A/CloudDocs
    0x7fff3c17a000 -     0x7fff3c183ff3  com.apple.CommonAuth (4.0 - 2.0) <4D237B25-27E5-3577-948B-073659F6D3C0> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
    0x7fff3c4bf000 -     0x7fff3c8c7fff  com.apple.CoreAUC (259.0.0 - 259.0.0) <1E0FB2C7-109E-3924-8E7F-8C6ACD78AF26> /System/Library/PrivateFrameworks/CoreAUC.framework/Versions/A/CoreAUC
    0x7fff3c8c8000 -     0x7fff3c8f8ff7  com.apple.CoreAVCHD (5.9.0 - 5900.4.1) <E9FF9574-122A-3966-AA2B-546E512ACD06> /System/Library/PrivateFrameworks/CoreAVCHD.framework/Versions/A/CoreAVCHD
    0x7fff3c98e000 -     0x7fff3c9d0ff3  com.apple.corebrightness (1.0 - 1) <8CD236FB-CFC9-352A-B5A6-2DB4226CD806> /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness
    0x7fff3cc86000 -     0x7fff3cc96ff7  com.apple.CoreEmoji (1.0 - 69.3) <A4357F5C-0C38-3A61-B456-D7321EB2CEE5> /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
    0x7fff3cf9a000 -     0x7fff3cfb0ff7  com.apple.CoreMediaAuthoring (2.2 - 956) <FBA28A76-97E2-3023-A3F6-D03280AE2889> /System/Library/PrivateFrameworks/CoreMediaAuthoring.framework/Versions/A/CoreMediaAuthoring
    0x7fff3d0f9000 -     0x7fff3d156ff7  com.apple.CoreNLP (1.0 - 130.5.4) <1FDB3609-F745-3874-84EB-473570632E50> /System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/CoreNLP
    0x7fff3d2df000 -     0x7fff3d2e4ff7  com.apple.CoreOptimization (1.0 - 1) <785B622B-8F7D-3B4D-83AF-EB98CB79FFF6> /System/Library/PrivateFrameworks/CoreOptimization.framework/Versions/A/CoreOptimization
    0x7fff3d2e5000 -     0x7fff3d38afff  com.apple.CorePDF (4.0 - 414) <D64D17C3-9AD0-3A29-89DE-36BEF0156381> /System/Library/PrivateFrameworks/CorePDF.framework/Versions/A/CorePDF
    0x7fff3d433000 -     0x7fff3d48ffff  com.apple.CorePrediction (1.0 - 1) <A26425DF-E222-333B-8CAE-6141A58B172C> /System/Library/PrivateFrameworks/CorePrediction.framework/Versions/A/CorePrediction
    0x7fff3d5bd000 -     0x7fff3d5eeff3  com.apple.CoreServicesInternal (309.1 - 309.1) <4ECD14EA-A493-3B84-A32F-CF928474A405> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7fff3d92b000 -     0x7fff3d9bcfff  com.apple.CoreSymbolication (9.3 - 64026) <BAF3CE6E-8140-3159-BF1B-B953816459A0> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
    0x7fff3da3f000 -     0x7fff3db74fff  com.apple.coreui (2.1 - 494.1) <B2C515C3-FCE8-3B28-A225-05AD917F509B> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7fff3db75000 -     0x7fff3dca6fff  com.apple.CoreUtils (5.6 - 560.11) <1A02D6F0-8C65-3FAE-AD63-56477EDE4773> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
    0x7fff3dcfb000 -     0x7fff3dd5ffff  com.apple.framework.CoreWiFi (13.0 - 1350.1) <6EC5DEB3-6E2F-3DC2-BE59-1FD05175FB0C> /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi
    0x7fff3dd60000 -     0x7fff3dd70ff7  com.apple.CrashReporterSupport (10.13 - 1) <A909F468-0648-3F51-A77E-3F9ADBC9A941> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fff3ddee000 -     0x7fff3ddfdff7  com.apple.framework.DFRFoundation (1.0 - 191.7) <3B8ED6F7-5DFF-34C3-BA90-DDB85679684C> /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
    0x7fff3de00000 -     0x7fff3de04ffb  com.apple.DSExternalDisplay (3.1 - 380) <901B7F6D-376A-3848-99D0-170C4D00F776> /System/Library/PrivateFrameworks/DSExternalDisplay.framework/Versions/A/DSExternalDisplay
    0x7fff3de86000 -     0x7fff3defcfff  com.apple.datadetectorscore (7.0 - 590.3) <26835841-E532-3930-A3F8-CE8DA0B244E3> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fff3df4a000 -     0x7fff3df8aff7  com.apple.DebugSymbols (181.0 - 181.0) <299A0238-ED78-3676-B131-274D972824AA> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
    0x7fff3df8b000 -     0x7fff3e0bafff  com.apple.desktopservices (1.12.5 - 1.12.5) <8AC3EBBD-3B50-3B6F-AF95-0196F97EA713> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
    0x7fff3e385000 -     0x7fff3e389ff7  com.apple.DisplayServicesFW (3.1 - 380) <6F0B8AC6-7E62-3DFC-B373-BF04833724C0> /System/Library/PrivateFrameworks/DisplayServices.framework/Versions/A/DisplayServices
    0x7fff3eed2000 -     0x7fff3f300fff  com.apple.vision.FaceCore (3.3.2 - 3.3.2) <B574FE33-4A41-3611-9738-388EBAF03E37> /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
    0x7fff3f333000 -     0x7fff3f3bcff3  com.apple.FileProvider (125.15 - 125.15) <2E707F97-6271-3561-8A94-54412293B783> /System/Library/PrivateFrameworks/FileProvider.framework/Versions/A/FileProvider
    0x7fff40f5c000 -     0x7fff40f5cfff  libmetal_timestamp.dylib (802.4.5) <013C2314-3F0B-311E-BA35-66FB4B0C56A9> /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/3802/Libraries/libmetal_timestamp.dylib
    0x7fff425c8000 -     0x7fff425cdff7  com.apple.GPUWrangler (3.18.52 - 3.18.52) <FCDE73DB-4663-3E3E-BFDA-B51648967AB5> /System/Library/PrivateFrameworks/GPUWrangler.framework/Versions/A/GPUWrangler
    0x7fff42981000 -     0x7fff429a6ff3  com.apple.GenerationalStorage (2.0 - 285.3) <13B96400-FF70-376B-B20E-FB7D61064800> /System/Library/PrivateFrameworks/GenerationalStorage.framework/Versions/A/GenerationalStorage
    0x7fff43343000 -     0x7fff43352fff  com.apple.GraphVisualizer (1.0 - 5) <B993B8A2-5700-3DFC-9EB7-4CCEE8F959F1> /System/Library/PrivateFrameworks/GraphVisualizer.framework/Versions/A/GraphVisualizer
    0x7fff433d5000 -     0x7fff43449fff  com.apple.Heimdal (4.0 - 2.0) <18607D75-DB78-3CC7-947E-AC769195164C> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
    0x7fff43d58000 -     0x7fff43d5fff7  com.apple.IOAccelerator (378.18.1 - 378.18.1) <F37B8021-DA55-3FA2-921F-59D49CAA2DFC> /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
    0x7fff43d63000 -     0x7fff43d7afff  com.apple.IOPresentment (1.0 - 35.1) <534F12C3-3585-3637-BE16-48891FCAEB7A> /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
    0x7fff44145000 -     0x7fff4416bffb  com.apple.IconServices (97.6 - 97.6) <A56D826D-20D2-34BE-AACC-A80CFCB4E915> /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices
    0x7fff44278000 -     0x7fff4427bff3  com.apple.InternationalSupport (1.0 - 1) <5AB382FD-BF81-36A1-9565-61F1FD398ECA> /System/Library/PrivateFrameworks/InternationalSupport.framework/Versions/A/InternationalSupport
    0x7fff442e9000 -     0x7fff442f9ffb  com.apple.IntlPreferences (2.0 - 227.5.2) <DA6BC4CA-14F5-3A83-82B6-812344A050D2> /System/Library/PrivateFrameworks/IntlPreferences.framework/Versions/A/IntlPreferences
    0x7fff44404000 -     0x7fff444f9ff7  com.apple.LanguageModeling (1.0 - 159.5.3) <7F0AC200-E3DD-39FB-8A95-00DD70B66A9F> /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
    0x7fff444fa000 -     0x7fff4453cfff  com.apple.Lexicon-framework (1.0 - 33.5) <DC94CF9E-1EB4-3C0E-B298-CA1190885276> /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon
    0x7fff44540000 -     0x7fff44547ff7  com.apple.LinguisticData (1.0 - 238.3) <49A54649-1021-3DBD-99B8-1B2EDFFA5378> /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData
    0x7fff44d46000 -     0x7fff44d49fff  com.apple.Mangrove (1.0 - 1) <27D6DF76-B5F8-3443-8826-D25B284331BF> /System/Library/PrivateFrameworks/Mangrove.framework/Versions/A/Mangrove
    0x7fff45258000 -     0x7fff452c1ff7  com.apple.gpusw.MetalTools (1.0 - 1) <B5F66CF4-BE75-3A0B-A6A0-2F22C7C259D9> /System/Library/PrivateFrameworks/MetalTools.framework/Versions/A/MetalTools
    0x7fff452ca000 -     0x7fff452e1ff7  com.apple.MobileAssets (1.0 - 437.60.1) <5FFD8A8B-F33F-3FA9-8F50-31C24A67862C> /System/Library/PrivateFrameworks/MobileAsset.framework/Versions/A/MobileAsset
    0x7fff4543d000 -     0x7fff45456fff  com.apple.MobileKeyBag (2.0 - 1.0) <828D360F-B6C6-34C3-8DE2-840664685081> /System/Library/PrivateFrameworks/MobileKeyBag.framework/Versions/A/MobileKeyBag
    0x7fff454e2000 -     0x7fff4550cffb  com.apple.MultitouchSupport.framework (1404.4 - 1404.4) <45374A2A-C0BC-3A70-8183-37295205CDFA> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
    0x7fff45773000 -     0x7fff4577efff  com.apple.NetAuth (6.2 - 6.2) <B3795F63-C14A-33E1-9EE6-02A2E7661321> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fff47012000 -     0x7fff47022ffb  com.apple.PerformanceAnalysis (1.194 - 194) <2844933E-B71C-3BE9-9A84-27B29E111F13> /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
    0x7fff48de0000 -     0x7fff48dfefff  com.apple.ProtocolBuffer (1 - 260) <40704740-4A53-3010-A49B-08D1D69D1D5E> /System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer
    0x7fff48f6b000 -     0x7fff48f81ff7  com.apple.QuickLookThumbnailing (1.0 - 1) <8F0092E4-6494-349D-B4C9-494DF293D716> /System/Library/PrivateFrameworks/QuickLookThumbnailing.framework/Versions/A/QuickLookThumbnailing
    0x7fff48fcc000 -     0x7fff48fd8fff  com.apple.xpc.RemoteServiceDiscovery (1.0 - 1205.60.9) <12E89ED2-E3E8-37CB-B4D8-C44E40285A3E> /System/Library/PrivateFrameworks/RemoteServiceDiscovery.framework/Versions/A/RemoteServiceDiscovery
    0x7fff48fd9000 -     0x7fff48ffcffb  com.apple.RemoteViewServices (2.0 - 125) <592323D1-CB44-35F1-9921-4C2AB8D920A0> /System/Library/PrivateFrameworks/RemoteViewServices.framework/Versions/A/RemoteViewServices
    0x7fff48ffd000 -     0x7fff49011ff7  com.apple.xpc.RemoteXPC (1.0 - 1205.60.9) <91DBCE29-743E-3D48-8D16-A8B497750D13> /System/Library/PrivateFrameworks/RemoteXPC.framework/Versions/A/RemoteXPC
    0x7fff4a918000 -     0x7fff4aa2bfff  com.apple.Sharing (1050.21 - 1050.21) <D0C80C0B-8B70-3780-9231-31725AFAEA65> /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
    0x7fff4aa56000 -     0x7fff4aa57ff7  com.apple.performance.SignpostNotification (1.2.5 - 2.5) <64CBA369-15D5-3A08-AFE8-B5D093974C68> /System/Library/PrivateFrameworks/SignpostNotification.framework/Versions/A/SignpostNotification
    0x7fff4b7a0000 -     0x7fff4ba3cfff  com.apple.SkyLight (1.600.0 - 312.62) <66F27586-E5CF-3147-9AC6-793B264DE29D> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7fff4c205000 -     0x7fff4c212fff  com.apple.SpeechRecognitionCore (4.6.1 - 4.6.1) <87EE7AB5-6925-3D21-BE00-F155CB457699> /System/Library/PrivateFrameworks/SpeechRecognitionCore.framework/Versions/A/SpeechRecognitionCore
    0x7fff4c2c4000 -     0x7fff4c502ff3  com.apple.spotlight.index (10.7.0 - 1191.4.13) <14C6EDFD-B843-35A4-AEA6-F485D756FF88> /System/Library/PrivateFrameworks/SpotlightIndex.framework/Versions/A/SpotlightIndex
    0x7fff4c6be000 -     0x7fff4c6e5fff  com.apple.StreamingZip (1.0 - 1) <32F550C9-3DF8-3DF9-A1EC-699C3D32621B> /System/Library/PrivateFrameworks/StreamingZip.framework/Versions/A/StreamingZip
    0x7fff4cdb7000 -     0x7fff4ce40fc7  com.apple.Symbolication (9.3 - 64033) <FAA17252-6378-34A4-BBBB-22DF54EC1626> /System/Library/PrivateFrameworks/Symbolication.framework/Versions/A/Symbolication
    0x7fff4ce51000 -     0x7fff4ce59ffb  com.apple.SymptomDiagnosticReporter (1.0 - 820.60.2) <66326935-2A3F-3482-B75F-AEB4CBA08DCF> /System/Library/PrivateFrameworks/SymptomDiagnosticReporter.framework/Versions/A/SymptomDiagnosticReporter
    0x7fff4d3b1000 -     0x7fff4d3b9ff7  com.apple.TCC (1.0 - 1) <E1EB7272-FE6F-39AB-83CA-B2B5F2A88D9B> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
    0x7fff4d5c6000 -     0x7fff4d683ff7  com.apple.TextureIO (3.7 - 3.7) <F8BAC954-405D-3CC3-AB7B-048C866EF980> /System/Library/PrivateFrameworks/TextureIO.framework/Versions/A/TextureIO
    0x7fff4d734000 -     0x7fff4d8e3fff  com.apple.UIFoundation (1.0 - 547.5) <E8FD9325-F415-3DF9-8C64-425EE2C58822> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
    0x7fff4e5b8000 -     0x7fff4e687ff7  com.apple.ViewBridge (343.2 - 343.2) <5519FCED-1F88-3BE6-9BE1-69992086B01B> /System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/ViewBridge
    0x7fff4edad000 -     0x7fff4ee0dfff  com.apple.xquery (1.3.1 - 30) <A335A70D-3859-3EAD-B85B-AF65B3A5A66E> /System/Library/PrivateFrameworks/XQuery.framework/Versions/A/XQuery
    0x7fff4efec000 -     0x7fff4efeeffb  com.apple.loginsupport (1.0 - 1) <D1232C1B-80EA-3DF8-9466-013695D0846E> /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
    0x7fff4f155000 -     0x7fff4f188ff7  libclosured.dylib (551.3) <DC3DA678-9C40-339C-A9C6-32AB74FCC682> /usr/lib/closure/libclosured.dylib
    0x7fff4f242000 -     0x7fff4f27bff7  libCRFSuite.dylib (41) <FE5EDB68-2593-3C2E-BBAF-1C52D206F296> /usr/lib/libCRFSuite.dylib
    0x7fff4f27c000 -     0x7fff4f287fff  libChineseTokenizer.dylib (28) <53633C9B-A3A8-36F7-A53C-432D802F4BB8> /usr/lib/libChineseTokenizer.dylib
    0x7fff4f319000 -     0x7fff4f31aff3  libDiagnosticMessagesClient.dylib (104) <9712E980-76EE-3A89-AEA6-DF4BAF5C0574> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff4f351000 -     0x7fff4f51bff3  libFosl_dynamic.dylib (17.8) <C58ED77A-4986-31C2-994C-34DDFB8106F0> /usr/lib/libFosl_dynamic.dylib
    0x7fff4f553000 -     0x7fff4f553fff  libOpenScriptingUtil.dylib (174) <610F0242-7CE5-3C86-951B-B646562694AF> /usr/lib/libOpenScriptingUtil.dylib
    0x7fff4f68a000 -     0x7fff4f68effb  libScreenReader.dylib (562.18.4) <E239923D-54C9-3BBF-852F-87C09DEF4091> /usr/lib/libScreenReader.dylib
    0x7fff4f68f000 -     0x7fff4f690ffb  libSystem.B.dylib (1252.50.4) <CDA73F3E-2A7D-3354-818A-580317A03255> /usr/lib/libSystem.B.dylib
    0x7fff4f70f000 -     0x7fff4f710fff  libThaiTokenizer.dylib (2.2) <6F416F41-BF77-3078-A05C-AFF5DA5AB008> /usr/lib/libThaiTokenizer.dylib
    0x7fff4f723000 -     0x7fff4f723fff  libapple_crypto.dylib (109.50.14) <48BA2E76-BF2F-3522-A54E-D7FB7EAF7A57> /usr/lib/libapple_crypto.dylib
    0x7fff4f724000 -     0x7fff4f73aff7  libapple_nghttp2.dylib (1.24) <01402BC4-4822-3676-9C80-50D83F816424> /usr/lib/libapple_nghttp2.dylib
    0x7fff4f73b000 -     0x7fff4f765ff3  libarchive.2.dylib (54) <8FC28DD8-E315-3C3E-95FE-D1D2CBE49888> /usr/lib/libarchive.2.dylib
    0x7fff4f766000 -     0x7fff4f7e7fdf  libate.dylib (1.13.1) <178ACDAD-DE7E-346C-A613-1CBF7929AC07> /usr/lib/libate.dylib
    0x7fff4f7eb000 -     0x7fff4f7ebff3  libauto.dylib (187) <A05C7900-F8C7-3E75-8D3F-909B40C19717> /usr/lib/libauto.dylib
    0x7fff4f7ec000 -     0x7fff4f8a4ff3  libboringssl.dylib (109.50.14) <E6813F87-B5E4-3F7F-A725-E6A7F2BD02EC> /usr/lib/libboringssl.dylib
    0x7fff4f8a5000 -     0x7fff4f8b5ff3  libbsm.0.dylib (39) <6BC96A72-AFBE-34FD-91B1-748A530D8AE6> /usr/lib/libbsm.0.dylib
    0x7fff4f8b6000 -     0x7fff4f8c3ffb  libbz2.1.0.dylib (38) <0A5086BB-4724-3C14-979D-5AD4F26B5B45> /usr/lib/libbz2.1.0.dylib
    0x7fff4f8c4000 -     0x7fff4f91afff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff4f91b000 -     0x7fff4f93fff7  libc++abi.dylib (400.8.2) <EF5E37D7-11D9-3530-BE45-B986612D13E2> /usr/lib/libc++abi.dylib
    0x7fff4f941000 -     0x7fff4f951fff  libcmph.dylib (6) <A5509EE8-7E00-3224-8814-015B077A3CF5> /usr/lib/libcmph.dylib
    0x7fff4f952000 -     0x7fff4f969fcf  libcompression.dylib (47.60.2) <543F07BF-2F2F-37D5-9866-E84BF659885B> /usr/lib/libcompression.dylib
    0x7fff4fc14000 -     0x7fff4fc2cff7  libcoretls.dylib (155.50.1) <D350052E-DC4D-3185-ADBA-BA48EDCEE955> /usr/lib/libcoretls.dylib
    0x7fff4fc2d000 -     0x7fff4fc2eff3  libcoretls_cfhelpers.dylib (155.50.1) <B297F5D8-F2FE-3566-A752-E9D998B9C039> /usr/lib/libcoretls_cfhelpers.dylib
    0x7fff500ff000 -     0x7fff50155ff3  libcups.2.dylib (462.2.1) <5FD94468-FC3C-32DC-8EF5-EFDC2815FE85> /usr/lib/libcups.2.dylib
    0x7fff50295000 -     0x7fff50295fff  libenergytrace.dylib (16) <A92AB8B8-B986-3CE6-980D-D55090FEF387> /usr/lib/libenergytrace.dylib
    0x7fff502c7000 -     0x7fff502cbff7  libgermantok.dylib (17) <37C1C061-5214-3050-9C3A-783A784435A8> /usr/lib/libgermantok.dylib
    0x7fff502cc000 -     0x7fff502d1ff3  libheimdal-asn1.dylib (520.50.6) <E358445A-B84E-31B5-BCCD-7E1397519D96> /usr/lib/libheimdal-asn1.dylib
    0x7fff502fd000 -     0x7fff503eeff7  libiconv.2.dylib (51.50.1) <2FEC9707-3FAF-3828-A50D-8605086D060F> /usr/lib/libiconv.2.dylib
    0x7fff503ef000 -     0x7fff50616ffb  libicucore.A.dylib (59180.0.1) <49C253CB-1BEF-3FF6-ABAB-7BACEEDE8C94> /usr/lib/libicucore.A.dylib
    0x7fff50663000 -     0x7fff50664fff  liblangid.dylib (128) <39C39393-0D05-301D-93B2-F224FC4949AA> /usr/lib/liblangid.dylib
    0x7fff50665000 -     0x7fff5067effb  liblzma.5.dylib (10) <3D419A50-961F-37D2-8A01-3DC7AB7B8D18> /usr/lib/liblzma.5.dylib
    0x7fff5067f000 -     0x7fff50695ff7  libmarisa.dylib (9) <D6D2D55D-1D2E-3442-B152-B18803C0ABB4> /usr/lib/libmarisa.dylib
    0x7fff50696000 -     0x7fff50745fff  libmecab.1.0.0.dylib (779.7.6) <334D4742-BDDD-3C2D-BBEB-85B32643BFA0> /usr/lib/libmecab.1.0.0.dylib
    0x7fff50746000 -     0x7fff5096eff7  libmecabra.dylib (779.7.6) <F462F170-E872-3D09-B219-973D5E99C09F> /usr/lib/libmecabra.dylib
    0x7fff50b46000 -     0x7fff50cc0fff  libnetwork.dylib (1229.60.3) <6E469F8A-963B-399D-9053-4883D2EECF4E> /usr/lib/libnetwork.dylib
    0x7fff50d47000 -     0x7fff511357e7  libobjc.A.dylib (723) <DD9E5EC5-B507-3249-B700-93433E2D5EDF> /usr/lib/libobjc.A.dylib
    0x7fff51148000 -     0x7fff5114cfff  libpam.2.dylib (22) <7B4D2CE2-1438-387A-9802-5CEEFBF26F86> /usr/lib/libpam.2.dylib
    0x7fff5114f000 -     0x7fff51183fff  libpcap.A.dylib (79.20.1) <FA13918B-A247-3181-B256-9B852C7BA316> /usr/lib/libpcap.A.dylib
    0x7fff51184000 -     0x7fff511c1fff  libpcre.0.dylib (9) <435CC540-20A7-3324-B757-E7209FE84303> /usr/lib/libpcre.0.dylib
    0x7fff51202000 -     0x7fff5121effb  libresolv.9.dylib (65) <E8F3415B-4472-3202-8901-41FD87981DB2> /usr/lib/libresolv.9.dylib
    0x7fff5126d000 -     0x7fff5126eff3  libspindump.dylib (252) <D8E27057-E3CC-3D7F-A010-4A87830F6A83> /usr/lib/libspindump.dylib
    0x7fff5126f000 -     0x7fff51402ff7  libsqlite3.dylib (274.8.1) <FCAD6A57-829E-3701-B16E-1833D620E0E8> /usr/lib/libsqlite3.dylib
    0x7fff51504000 -     0x7fff51552fff  libstdc++.6.0.9.dylib (104.1) <0EA35E7E-B536-3628-B462-A4098805CEAC> /usr/lib/libstdc++.6.0.9.dylib
    0x7fff515d6000 -     0x7fff51636ff3  libusrtcp.dylib (1229.60.3) <584152F4-EDC1-388A-9134-95147E8ABC49> /usr/lib/libusrtcp.dylib
    0x7fff51637000 -     0x7fff5163affb  libutil.dylib (51.20.1) <216D18E5-0BAF-3EAF-A38E-F6AC37CBABD9> /usr/lib/libutil.dylib
    0x7fff5163b000 -     0x7fff51648fff  libxar.1.dylib (400) <0316128D-3B47-3052-995D-97B4FE5491DC> /usr/lib/libxar.1.dylib
    0x7fff5164c000 -     0x7fff51733fff  libxml2.2.dylib (31.10) <503721DB-0D8D-379E-B743-18CE59304155> /usr/lib/libxml2.2.dylib
    0x7fff51734000 -     0x7fff5175cfff  libxslt.1.dylib (15.12) <4A5E011D-8B29-3135-A52B-9A9070ABD752> /usr/lib/libxslt.1.dylib
    0x7fff5175d000 -     0x7fff5176fffb  libz.1.dylib (70) <48C67CFC-940D-3857-8DAD-857774605352> /usr/lib/libz.1.dylib
    0x7fff5180b000 -     0x7fff5180fff7  libcache.dylib (80) <092479CB-1008-3A83-BECF-E115F24D13C1> /usr/lib/system/libcache.dylib
    0x7fff51810000 -     0x7fff5181aff3  libcommonCrypto.dylib (60118.50.1) <029F5985-9B6E-3DCB-9B96-FD007678C6A7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff5181b000 -     0x7fff51822fff  libcompiler_rt.dylib (62) <968B8E3F-3681-3230-9D78-BB8732024F6E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff51823000 -     0x7fff5182cffb  libcopyfile.dylib (146.50.5) <3885083D-50D8-3EEC-B481-B2E605180D7F> /usr/lib/system/libcopyfile.dylib
    0x7fff5182d000 -     0x7fff518b2fff  libcorecrypto.dylib (562.50.17) <67007279-24E1-3F30-802D-A55CD5C27946> /usr/lib/system/libcorecrypto.dylib
    0x7fff5193a000 -     0x7fff51973ff7  libdispatch.dylib (913.60.2) <414353F7-3A9F-3091-AFCE-E66F74687D5D> /usr/lib/system/libdispatch.dylib
    0x7fff51974000 -     0x7fff51991ff7  libdyld.dylib (551.3) <CF59A5A5-288B-30E6-BD42-9056B4E4139A> /usr/lib/system/libdyld.dylib
    0x7fff51992000 -     0x7fff51992ffb  libkeymgr.dylib (28) <E34E283E-90FA-3C59-B48E-1277CDB9CDCE> /usr/lib/system/libkeymgr.dylib
    0x7fff51993000 -     0x7fff5199fff3  libkxld.dylib (4570.61.1) <E394563E-F5D5-338D-B733-445A553E6327> /usr/lib/system/libkxld.dylib
    0x7fff519a0000 -     0x7fff519a0ff7  liblaunch.dylib (1205.60.9) <4B2943A9-0994-3E8B-94B8-98DA9CED0021> /usr/lib/system/liblaunch.dylib
    0x7fff519a1000 -     0x7fff519a5ffb  libmacho.dylib (906) <1902A611-081A-3452-B11E-EBD1B166E831> /usr/lib/system/libmacho.dylib
    0x7fff519a6000 -     0x7fff519a8ff3  libquarantine.dylib (86) <26C0BA22-8F93-3A07-9A4E-C8D53D2CE42E> /usr/lib/system/libquarantine.dylib
    0x7fff519a9000 -     0x7fff519aaff3  libremovefile.dylib (45) <711E18B2-5BBE-3211-A916-56740C27D17A> /usr/lib/system/libremovefile.dylib
    0x7fff519ab000 -     0x7fff519c2fff  libsystem_asl.dylib (356.50.1) <3B24F2D1-B578-359D-ADB2-0ED19A364C38> /usr/lib/system/libsystem_asl.dylib
    0x7fff519c3000 -     0x7fff519c3fff  libsystem_blocks.dylib (67) <17303FDF-0D2D-3963-B05E-B4DF63052D47> /usr/lib/system/libsystem_blocks.dylib
    0x7fff519c4000 -     0x7fff51a4dff7  libsystem_c.dylib (1244.50.9) <1187BFE8-4576-3247-8177-481554E1F9E7> /usr/lib/system/libsystem_c.dylib
    0x7fff51a4e000 -     0x7fff51a51ffb  libsystem_configuration.dylib (963.50.8) <DF6B5287-203E-30CB-9947-78DF446C72B8> /usr/lib/system/libsystem_configuration.dylib
    0x7fff51a52000 -     0x7fff51a55ffb  libsystem_coreservices.dylib (51) <486000D3-D8CB-3BE7-8EE5-8BF380DE6DF7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff51a56000 -     0x7fff51a57fff  libsystem_darwin.dylib (1244.50.9) <09C21A4A-9EE0-388B-A9D9-DFF8F6758791> /usr/lib/system/libsystem_darwin.dylib
    0x7fff51a58000 -     0x7fff51a5eff7  libsystem_dnssd.dylib (878.50.17) <C12E2075-3E4B-3187-8B3B-F6150FCB82E0> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff51a5f000 -     0x7fff51aa8ff7  libsystem_info.dylib (517.30.1) <AB634A98-B8AA-3804-8436-38261FC8EC4D> /usr/lib/system/libsystem_info.dylib
    0x7fff51aa9000 -     0x7fff51acfff7  libsystem_kernel.dylib (4570.61.1) <D7F2010A-EA32-3F62-90DE-85E3C5CC3065> /usr/lib/system/libsystem_kernel.dylib
    0x7fff51ad0000 -     0x7fff51b1bfcb  libsystem_m.dylib (3147.50.1) <8CFB51C9-B422-3379-8552-064C63943A23> /usr/lib/system/libsystem_m.dylib
    0x7fff51b1c000 -     0x7fff51b3bfff  libsystem_malloc.dylib (140.50.6) <7FD43735-9DDD-300E-8C4A-F909A74BDF49> /usr/lib/system/libsystem_malloc.dylib
    0x7fff51b3c000 -     0x7fff51c6cff7  libsystem_network.dylib (1229.60.3) <D17B38B7-BE5D-3A9C-9257-F045E7647E8A> /usr/lib/system/libsystem_network.dylib
    0x7fff51c6d000 -     0x7fff51c77ffb  libsystem_networkextension.dylib (767.60.1) <1745C91F-9AF0-357D-BD40-34451A2D6A5E> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff51c78000 -     0x7fff51c81ff3  libsystem_notify.dylib (172) <08012EC0-2CD2-34BE-BF93-E7F56491299A> /usr/lib/system/libsystem_notify.dylib
    0x7fff51c82000 -     0x7fff51c89ff7  libsystem_platform.dylib (161.50.1) <6355EE2D-5456-3CA8-A227-B96E8F1E2AF8> /usr/lib/system/libsystem_platform.dylib
    0x7fff51c8a000 -     0x7fff51c95fff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff51c96000 -     0x7fff51c99fff  libsystem_sandbox.dylib (765.60.1) <E5DE4B2F-202D-3474-9F08-7CAB1501D411> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff51c9a000 -     0x7fff51c9bff3  libsystem_secinit.dylib (30) <DE8D14E8-A276-3FF8-AE13-77F7040F33C1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff51c9c000 -     0x7fff51ca3ff7  libsystem_symptoms.dylib (820.60.2) <9C9E82AB-D1EE-3EC7-B20E-44338CE092AC> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff51ca4000 -     0x7fff51cb7fff  libsystem_trace.dylib (829.50.17) <6568D68B-1D4C-38EE-90A9-54821D6403C0> /usr/lib/system/libsystem_trace.dylib
    0x7fff51cb9000 -     0x7fff51cbeff7  libunwind.dylib (35.3) <BEF3FB49-5604-3B5F-82B5-332B80023AC3> /usr/lib/system/libunwind.dylib
    0x7fff51cbf000 -     0x7fff51cecfff  libxpc.dylib (1205.60.9) <16132357-B57A-35F5-B165-487D3F759F45> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 12
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 5970
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=431.2M resident=0K(0%) swapped_out_or_unallocated=431.2M(100%)
Writable regions: Total=252.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=252.8M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework              1024K        8 
Activity Tracing                   256K        2 
CG backing stores                 3724K       10 
CG image                           864K       61 
CoreAnimation                     3732K      113 
CoreGraphics                         8K        2 
CoreImage                           40K        7 
CoreUI image data                 5316K       41 
CoreUI image file                  292K        5 
Foundation                           4K        2 
Image IO                          2320K        7 
Kernel Alloc Once                    8K        2 
MALLOC                           221.0M       64 
MALLOC guard page                   80K       17 
Memory Tag 242                      12K        2 
Memory Tag 251                      24K        2 
SQLite page cache                   64K        2 
STACK GUARD                       56.1M       17 
Stack                             15.6M       17 
VM_ALLOCATE                        356K       31 
__DATA                            32.2M      301 
__FONT_DATA                          4K        2 
__LINKEDIT                       198.0M       19 
__TEXT                           233.1M      299 
__UNICODE                          560K        2 
libnetwork                         128K        2 
mapped file                       62.9M      281 
shared memory                      684K       24 
===========                     =======  ======= 
TOTAL                            837.9M     1314 

Model: MacBookPro11,4, BootROM MBP114.0183.B00, 4 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.29f24
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.77.37.31.1a9)
Bluetooth: Version 6.0.6f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Thunderbolt Ethernet, Ethernet, en4
Network Service: Wi-Fi, AirPort, en0
PCI Card: Apple 57762-A0, Ethernet Controller, Thunderbolt@195,0,0
Serial ATA Device: APPLE SSD SM0256G, 251 GB
USB Device: USB 3.0 Bus
USB Device: USB3.0 Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
USB Device: HD Pro Webcam C920
USB Device: USB2.0 Hub
USB Device: Das Keyboard
USB Device: C-Media USB Audio Device
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1
Thunderbolt Device: Thunderbolt to Gigabit Ethernet Adapter, Apple Inc., 1, 5.5
```
</details>

I was trying to use the 'discard idle and continue' action.

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
Following from the result of preliminary investigation https://github.com/toggl/toggldesktop/issues/2506#issuecomment-452302800

This PR will introduce a **minimal** solution by introducing `ScopedLock` for `RelatedData.TimeEntries`.

### 🕶️ Types of changes
**Bug fix** (non-breaking change which fixes an issue)

### 🤯 List of changes
- [x] Lock the modification of TimeEntries vector in RelatedData class
- [x] Find the way to lock ~~all~~ few TimeEntries's iterators

### 👫 Relationships
Closes #2506 

### 🔎 Review hints
- Review code and make sure, if there are any threads are trying to modify the TimeEntries container, other threads should NOT iterate it.
- Logics are remain.

### CODE REVIEW

**Comment by NghiaTranUIT** [comment]
Basically, this PR is merely a tiny solution for the crash #2506. I won't guarantee that this PR will prevent the crash completely, which occurs by the read-write problem.

Full solution should be done in #2747 

---------------------------

Furthermore, I don't need to refactor all `TimeEntries`'s iterators due to this argument
> All const member functions can be called concurrently by different threads.
from https://embeddedartistry.com/blog/2017/8/2/an-overview-of-c-stl-containers

Fortunately, majority of the existing TimeEntries' iterators are calling from `const` member func.
Ex:
https://github.com/toggl/toggldesktop/blob/f817bd66a4761d4e1842af759ab02d8f72ac321c/src/user.cc#L264-L280
https://github.com/toggl/toggldesktop/blob/f817bd66a4761d4e1842af759ab02d8f72ac321c/src/user.cc#L403-L412

**Comment by NghiaTranUIT** [comment]
Ready to review 🙌

File: src/related_data.cc [hunk 1]
```diff
@@ -17,6 +17,7 @@
 #include "./task.h"
 #include "./time_entry.h"
 #include "./workspace.h"
+#include "Poco/RWLock.h"
```
Comment (IndrekV) [inline src/related_data.cc]: This `include` should not be needed as we don't use RWLock currently.
